# Interlingua translation for linuxmint
# Copyright (c) 2016 Rosetta Contributors and Canonical Ltd 2016
# This file is distributed under the same license as the linuxmint package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: linuxmint\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2023-11-27 14:33+0000\n"
"PO-Revision-Date: 2024-02-17 00:33+0000\n"
"Last-Translator: eduver <Unknown>\n"
"Language-Team: Interlingua <ia@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-12-05 10:14+0000\n"
"X-Generator: Launchpad (build 1519c6efe8e9bd78e6c5ebf2eb5bcb040b95ad32)\n"

#: lib/mintstick.py:312
msgid "The USB stick was formatted successfully."
msgstr "Le clave USB esseva formatate con bon successo."

#: lib/mintstick.py:315
#, python-format
msgid "An error occured while creating a partition on %s."
msgstr "Un error occurreva durante le creation de un partition sur %s."

#: lib/mintstick.py:317 lib/mintstick.py:427
msgid "Authentication Error."
msgstr "Error de authentication."

#: lib/mintstick.py:322 lib/mintstick.py:433
msgid "An error occurred."
msgstr "Un error occurreva."

#: lib/mintstick.py:420
msgid "The image was successfully written."
msgstr "Le imagine esseva scribite con bon successo."

#: lib/mintstick.py:423
msgid "Not enough space on the USB stick."
msgstr "Spatio insufficiente in le clave USB."

#: lib/mintstick.py:425
msgid "An error occured while copying the image."
msgstr "Un error occurreva durante le copia del imagine."

#: lib/verify.py:54
msgid "bytes"
msgstr "bytes"

#: lib/verify.py:54
msgid "KB"
msgstr "kB"

#: lib/verify.py:54
msgid "MB"
msgstr "MB"

#: lib/verify.py:54
msgid "GB"
msgstr "GB"

#: lib/verify.py:54
msgid "TB"
msgstr "TB"

#: lib/verify.py:87
msgid "ISO images"
msgstr "Imagines ISO"

#: lib/verify.py:91
msgid "Checksum files"
msgstr "Files de summa de controlo"

#: lib/verify.py:95
msgid "GPG signatures"
msgstr "Signaturas GPG"

#: lib/verify.py:107 lib/verify.py:108 lib/verify.py:109
msgid "Calculating..."
msgstr "Calculante..."

#: lib/verify.py:167
msgid "No volume ID found"
msgstr "Nulle ID de volumine trovate"

#: lib/verify.py:208
msgid "The checksum is correct"
msgstr "Le summa de controlo es correcte"

#: lib/verify.py:209
msgid ""
"The checksum is correct but the authenticity of the sum was not verified."
msgstr ""
"Le summa de controlo es correcte ma le authenticitate del summa non esseva "
"verificate."

#: lib/verify.py:211
msgid "Checksum mismatch"
msgstr "Disconcordantia del summa de controlo"

#: lib/verify.py:212
msgid "Download the ISO image again. Its checksum does not match."
msgstr "Discarga le imagine ISO de nove. Su summa de controlo non concorda."

#: lib/verify.py:223
msgid "The sums file could not be downloaded. Check the URL."
msgstr "Le file de summas non poteva esser discargate. Verifica le URL."

#: lib/verify.py:232
msgid "The gpg file could not be downloaded. Check the URL."
msgstr "Le file GPG non poteva esser descargate. Verifica le URL."

#: lib/verify.py:243
msgid "The sums file could not be checked."
msgstr "Le file de summas non poteva esser verificate."

#: lib/verify.py:250
msgid "The gpg file could not be checked."
msgstr "Le file gpg non poteva esser verificate."

#: lib/verify.py:260
msgid "Integrity check failed"
msgstr "Verification de integritate fallite"

#: lib/verify.py:269
msgid "The SHA256 sums file is not signed."
msgstr "Le file de summas SHA256 non es signate."

#: lib/verify.py:273
#, python-format
msgid "Signed by: %s"
msgstr "Signate per: %s"

#: lib/verify.py:287
msgid "Unknown signature"
msgstr "Signatura incognite"

#: lib/verify.py:288
msgid "Key not found on keyserver."
msgstr "Clave non trovate in le servitor de claves."

#: lib/verify.py:299 lib/verify.py:305
msgid "Everything looks good!"
msgstr "Toto pare ben!"

#: lib/verify.py:300
msgid "This is an official ISO image."
msgstr "Iste es un imagine ISO official."

#: lib/verify.py:306
msgid "This ISO image is verified by a trusted signature."
msgstr "Iste imagine ISO es verificate per un signatura fidite."

#: lib/verify.py:309
msgid "If you trust the signature you can trust the ISO."
msgstr "Si tu fide in le signatura, tu pote fider in le ISO."

#: lib/verify.py:310
msgid "Untrusted signature"
msgstr "Signatura non fidite"

#: lib/verify.py:311
msgid "This ISO image is verified by an untrusted signature."
msgstr "Iste imagine ISO es verificate per un signatura non fidite."

#: lib/verify.py:316
msgid "An error occurred"
msgstr "Un error occurreva"

#: lib/verify.py:327
msgid "The SHA256 sum of the ISO image is incorrect."
msgstr "Le summa SHA256 del imagine ISO es incorrecte."

#: lib/verify.py:328
msgid "The SHA256 sums file does not contain sums for this ISO image."
msgstr "Le file de summas SHA256 non contine summas pro iste imagine ISO."

#: generate_additional_files.py:22 generate_additional_files.py:34
#: share/mintstick/mintstick.ui.h:38
msgid "USB Image Writer"
msgstr "Scriptor de imagine USB"

#: generate_additional_files.py:22 generate_additional_files.py:34
#: generate_additional_files.py:67 share/mintstick/mintstick.ui.h:39
msgid "Make a bootable USB stick"
msgstr "Crear un clave USB bootabile"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: share/mintstick/mintstick.ui.h:27
msgid "USB Stick Formatter"
msgstr "Formatator de clave USB"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:28
msgid "Format a USB stick"
msgstr "Formatar un clave USB"

#: generate_additional_files.py:67
msgid "Make bootable USB stick"
msgstr "Crear clave USB bootabile"

#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:26
msgid "Format"
msgstr "Formatar"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:32
#: share/mintstick/verify.ui.h:7
msgid "Verify"
msgstr "Verificar"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:33
msgid "Verify the authenticity and integrity of the image"
msgstr "Verifica le authenticitate e integritate del imagine"

#: generate_additional_files.py:115 generate_additional_files.py:144
msgid ""
"This will destroy all data on the USB stick, are you sure you want to "
"proceed?"
msgstr ""
"Isto destruera tote le datos sur le clave USB, an tu es secur que tu vole "
"proceder?"

#: share/mintstick/mintstick.ui.h:1
msgid "USB stick:"
msgstr "Clave USB:"

#: share/mintstick/mintstick.ui.h:2
msgid "Filesystem:"
msgstr "Systema de files:"

#: share/mintstick/mintstick.ui.h:3
msgid "Select a USB stick"
msgstr "Seliger a clave USB"

#: share/mintstick/mintstick.ui.h:4
msgid ""
"FAT32 \n"
"  + Compatible everywhere.\n"
"  -  Cannot handle files larger than 4GB.\n"
"\n"
"exFAT\n"
"  + Compatible almost everywhere.\n"
"  + Can handle files larger than 4GB.\n"
"  -  Not as compatible as FAT32.\n"
"\n"
"NTFS \n"
"  + Compatible with Windows.\n"
"  -  Not compatible with Mac and most hardware devices.\n"
"  -  Occasional compatibility problems with Linux (NTFS is proprietary and "
"reverse engineered).\n"
"\n"
"EXT4 \n"
"  + Modern, stable, fast, journalized.\n"
"  + Supports Linux file permissions.\n"
"  -  Not compatible with Windows, Mac and most hardware devices.\n"
msgstr ""
"FAT32 \n"
"  + Compatibile ubique.\n"
"  -  Non  pote gerer files major de 4GB.\n"
"\n"
"exFAT\n"
"  + Compatibile quasi ubique.\n"
"  + Pote gerer files major de 4GB.\n"
"  -  Non assi compatibile como FAT32.\n"
"\n"
"NTFS \n"
"  + Compatibile con Windows.\n"
"  -  Non compatibile con Mac e plure dispositivos hardware.\n"
"  -  Occasional problemas de compatibilitate con Linux (NTFS es proprietari "
"e reverse ingenierisate).\n"
"\n"
"EXT4 \n"
"  + Moderne, stabile, rapide, journalisate.\n"
"  + Supporta le permissiones del files de Linux.\n"
"  -  Non compatibile con Windows, Mac  e plure dispositivos hardware.\n"

#: share/mintstick/mintstick.ui.h:23
msgid "Volume label:"
msgstr "Etiquetta de volumine:"

#: share/mintstick/mintstick.ui.h:24
msgid "Choose a name for your USB Stick"
msgstr "Elige un nomine pro tu clave USB"

#: share/mintstick/mintstick.ui.h:25
msgid "USB Stick"
msgstr "Clave USB"

#: share/mintstick/mintstick.ui.h:29
msgid "ISO image:"
msgstr "Imagine ISO:"

#: share/mintstick/mintstick.ui.h:30
msgid "Select an image"
msgstr "Seliger un imagine"

#: share/mintstick/mintstick.ui.h:31
msgid "Select Image"
msgstr "Seliger un imagine"

#: share/mintstick/mintstick.ui.h:34
msgid "Write"
msgstr "Scriber"

#: share/mintstick/mintstick.ui.h:35
msgid "This ISO looks like a Windows image."
msgstr "Iste ISO pare como un imagine de Windows."

#: share/mintstick/mintstick.ui.h:36
msgid "Windows images require special processing."
msgstr "Imagines de Windows require processamento special."

#: share/mintstick/mintstick.ui.h:37
msgid "More information"
msgstr "Plus information"

#: share/mintstick/verify.ui.h:1
msgid "ISO:"
msgstr "ISO:"

#: share/mintstick/verify.ui.h:2
msgid "Volume:"
msgstr "Volumine:"

#: share/mintstick/verify.ui.h:3
msgid "SHA256sum:"
msgstr "SHA256sum:"

#: share/mintstick/verify.ui.h:4
msgid "Size:"
msgstr "Dimension:"

#: share/mintstick/verify.ui.h:5
msgid "SHA256 sums file:"
msgstr "File de summas SHA256:"

#: share/mintstick/verify.ui.h:6
msgid "GPG signed file:"
msgstr "File signate per GPG:"

#: share/mintstick/verify.ui.h:8
msgid "URLs"
msgstr "URLs"

#: share/mintstick/verify.ui.h:9
msgid "SHA256 sums file"
msgstr "File de summas SHA256"

#: share/mintstick/verify.ui.h:10
msgid "GPG signed file"
msgstr "File signate per GPG"

#: share/mintstick/verify.ui.h:11
msgid "Local files"
msgstr "Files local"

#: share/mintstick/verify.ui.h:12
msgid "SHA256 sum"
msgstr "Summa SHA256"

#: share/mintstick/verify.ui.h:13
msgid "Check"
msgstr "Controlar"

#: share/mintstick/verify.ui.h:14
msgid "Checksum"
msgstr "Controlo de summa"

#: share/mintstick/verify.ui.h:15
msgid "Go back"
msgstr "Retroceder"

#: share/mintstick/verify.ui.h:16
msgid "ISO Verification"
msgstr "Verification de ISO"
