# Italian translation for linuxmint
# Copyright (c) 2013 Rosetta Contributors and Canonical Ltd 2013
# This file is distributed under the same license as the linuxmint package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: linuxmint\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2023-11-27 14:33+0000\n"
"PO-Revision-Date: 2022-12-03 17:48+0000\n"
"Last-Translator: Fs00 <Unknown>\n"
"Language-Team: Italian <it@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2025-01-06 11:56+0000\n"
"X-Generator: Launchpad (build 6394e03793719e8d73f5a60b5439440e693c92f1)\n"

#: lib/mintstick.py:312
msgid "The USB stick was formatted successfully."
msgstr "La penna USB è stata formattata con successo."

#: lib/mintstick.py:315
#, python-format
msgid "An error occured while creating a partition on %s."
msgstr ""
"Si è verificato un errore durante la creazione di una partizione su %s."

#: lib/mintstick.py:317 lib/mintstick.py:427
msgid "Authentication Error."
msgstr "Errore di autenticazione."

#: lib/mintstick.py:322 lib/mintstick.py:433
msgid "An error occurred."
msgstr "Si è verificato un errore."

#: lib/mintstick.py:420
msgid "The image was successfully written."
msgstr "L'immagine è stata scritta con successo."

#: lib/mintstick.py:423
msgid "Not enough space on the USB stick."
msgstr "Non c'è abbastanza spazio sulla penna USB."

#: lib/mintstick.py:425
msgid "An error occured while copying the image."
msgstr "Si è verificato un errore durante la copia dell'immagine."

#: lib/verify.py:54
msgid "bytes"
msgstr "byte"

#: lib/verify.py:54
msgid "KB"
msgstr "KB"

#: lib/verify.py:54
msgid "MB"
msgstr "MB"

#: lib/verify.py:54
msgid "GB"
msgstr "GB"

#: lib/verify.py:54
msgid "TB"
msgstr "TB"

#: lib/verify.py:87
msgid "ISO images"
msgstr "immagini ISO"

#: lib/verify.py:91
msgid "Checksum files"
msgstr "File di checksum"

#: lib/verify.py:95
msgid "GPG signatures"
msgstr "Firme GPG"

#: lib/verify.py:107 lib/verify.py:108 lib/verify.py:109
msgid "Calculating..."
msgstr "Calcolo..."

#: lib/verify.py:167
msgid "No volume ID found"
msgstr "Nessun ID volume trovato"

#: lib/verify.py:208
msgid "The checksum is correct"
msgstr "Il checksum è corretto"

#: lib/verify.py:209
msgid ""
"The checksum is correct but the authenticity of the sum was not verified."
msgstr ""
"Il checksum è corretto ma l'autenticità della somma non è verificata."

#: lib/verify.py:211
msgid "Checksum mismatch"
msgstr "Checksum non corrispondente"

#: lib/verify.py:212
msgid "Download the ISO image again. Its checksum does not match."
msgstr "Scarica di nuovo l'immagine ISO. Il suo checksum non corrisponde."

#: lib/verify.py:223
msgid "The sums file could not be downloaded. Check the URL."
msgstr "Impossibile scaricare il file delle somme. Controlla l'URL."

#: lib/verify.py:232
msgid "The gpg file could not be downloaded. Check the URL."
msgstr "Impossibile scaricare il file gpg. Controlla l'URL."

#: lib/verify.py:243
msgid "The sums file could not be checked."
msgstr "Impossibile controllare il file delle somme."

#: lib/verify.py:250
msgid "The gpg file could not be checked."
msgstr "Impossibile controllare il file gpg."

#: lib/verify.py:260
msgid "Integrity check failed"
msgstr "Controllo integrità fallito"

#: lib/verify.py:269
msgid "The SHA256 sums file is not signed."
msgstr "Il file delle somme SHA256 non è firmato."

#: lib/verify.py:273
#, python-format
msgid "Signed by: %s"
msgstr "Firmato da: %s"

#: lib/verify.py:287
msgid "Unknown signature"
msgstr "Firma sconosciuta"

#: lib/verify.py:288
msgid "Key not found on keyserver."
msgstr "Chiave non trovata sul server delle chiavi."

#: lib/verify.py:299 lib/verify.py:305
msgid "Everything looks good!"
msgstr "Sembra tutto corretto!"

#: lib/verify.py:300
msgid "This is an official ISO image."
msgstr "Questa è un'immagine ISO ufficiale."

#: lib/verify.py:306
msgid "This ISO image is verified by a trusted signature."
msgstr "Questa immagine ISO è verificata da una firma attendibile."

#: lib/verify.py:309
msgid "If you trust the signature you can trust the ISO."
msgstr "Se ti fidi della firma puoi fidarti dell'ISO."

#: lib/verify.py:310
msgid "Untrusted signature"
msgstr "Firma non attendibile"

#: lib/verify.py:311
msgid "This ISO image is verified by an untrusted signature."
msgstr "Questa immagine ISO è verificata da una firma non attendibile."

#: lib/verify.py:316
msgid "An error occurred"
msgstr "Si è verificato un errore"

#: lib/verify.py:327
msgid "The SHA256 sum of the ISO image is incorrect."
msgstr "La somma SHA256 dell'immagine ISO non è corretta."

#: lib/verify.py:328
msgid "The SHA256 sums file does not contain sums for this ISO image."
msgstr ""
"Il file delle somme SHA256 non contiene le somme per questa immagine ISO."

#: generate_additional_files.py:22 generate_additional_files.py:34
#: share/mintstick/mintstick.ui.h:38
msgid "USB Image Writer"
msgstr "Scrivi immagine su USB"

#: generate_additional_files.py:22 generate_additional_files.py:34
#: generate_additional_files.py:67 share/mintstick/mintstick.ui.h:39
msgid "Make a bootable USB stick"
msgstr "Crea una penna USB avviabile"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: share/mintstick/mintstick.ui.h:27
msgid "USB Stick Formatter"
msgstr "Formatta penna USB"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:28
msgid "Format a USB stick"
msgstr "Formatta una penna USB"

#: generate_additional_files.py:67
msgid "Make bootable USB stick"
msgstr "Crea penna USB avviabile"

#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:26
msgid "Format"
msgstr "Formatta"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:32
#: share/mintstick/verify.ui.h:7
msgid "Verify"
msgstr "Verifica"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:33
msgid "Verify the authenticity and integrity of the image"
msgstr "Verifica l'autenticità e l'integrità dell'immagine"

#: generate_additional_files.py:115 generate_additional_files.py:144
msgid ""
"This will destroy all data on the USB stick, are you sure you want to "
"proceed?"
msgstr ""
"Tutti i dati nella penna USB verranno cancellati, sei sicuro di voler "
"continuare?"

#: share/mintstick/mintstick.ui.h:1
msgid "USB stick:"
msgstr "Penna USB:"

#: share/mintstick/mintstick.ui.h:2
msgid "Filesystem:"
msgstr "Filesystem:"

#: share/mintstick/mintstick.ui.h:3
msgid "Select a USB stick"
msgstr "Seleziona una penna USB"

#: share/mintstick/mintstick.ui.h:4
msgid ""
"FAT32 \n"
"  + Compatible everywhere.\n"
"  -  Cannot handle files larger than 4GB.\n"
"\n"
"exFAT\n"
"  + Compatible almost everywhere.\n"
"  + Can handle files larger than 4GB.\n"
"  -  Not as compatible as FAT32.\n"
"\n"
"NTFS \n"
"  + Compatible with Windows.\n"
"  -  Not compatible with Mac and most hardware devices.\n"
"  -  Occasional compatibility problems with Linux (NTFS is proprietary and "
"reverse engineered).\n"
"\n"
"EXT4 \n"
"  + Modern, stable, fast, journalized.\n"
"  + Supports Linux file permissions.\n"
"  -  Not compatible with Windows, Mac and most hardware devices.\n"
msgstr ""
"FAT32 \n"
"  + Compatibile ovunque.\n"
"  -  Non può gestire file più grandi di 4GB.\n"
"\n"
"exFAT\n"
"  + Compatibile quasi ovunque.\n"
"  + Può gestire file più grandi di 4GB.\n"
"  -  Non così compatibile come FAT32.\n"
"\n"
"NTFS \n"
"  + Compatibile con Windows.\n"
"  -  Non compatibile con Mac e la maggior parte dei dispositivi hardware.\n"
"  -  Occasionali problemi di compatibilità con Linux (NTFS è proprietario e "
"reverse engineered).\n"
"\n"
"EXT4 \n"
"  + Moderno, stabile, veloce, journalized.\n"
"  + Supporta i permessi sui file di Linux.\n"
"  -  Non compatibile con Windows, Mac e la maggior parte dei dispositivi "
"hardware.\n"

#: share/mintstick/mintstick.ui.h:23
msgid "Volume label:"
msgstr "Etichetta del volume:"

#: share/mintstick/mintstick.ui.h:24
msgid "Choose a name for your USB Stick"
msgstr "Scegli un nome per la tua penna USB"

#: share/mintstick/mintstick.ui.h:25
msgid "USB Stick"
msgstr "Penna USB"

#: share/mintstick/mintstick.ui.h:29
msgid "ISO image:"
msgstr "Immagine ISO:"

#: share/mintstick/mintstick.ui.h:30
msgid "Select an image"
msgstr "Seleziona un'immagine"

#: share/mintstick/mintstick.ui.h:31
msgid "Select Image"
msgstr "Seleziona l'immagine"

#: share/mintstick/mintstick.ui.h:34
msgid "Write"
msgstr "Scrivi"

#: share/mintstick/mintstick.ui.h:35
msgid "This ISO looks like a Windows image."
msgstr "Questa ISO sembra un'immagine Windows."

#: share/mintstick/mintstick.ui.h:36
msgid "Windows images require special processing."
msgstr "Le immagini di Windows richiedono un'elaborazione speciale."

#: share/mintstick/mintstick.ui.h:37
msgid "More information"
msgstr "Maggiori informazioni"

#: share/mintstick/verify.ui.h:1
msgid "ISO:"
msgstr "ISO:"

#: share/mintstick/verify.ui.h:2
msgid "Volume:"
msgstr "Volume:"

#: share/mintstick/verify.ui.h:3
msgid "SHA256sum:"
msgstr "SHA256sum:"

#: share/mintstick/verify.ui.h:4
msgid "Size:"
msgstr "Dimensioni:"

#: share/mintstick/verify.ui.h:5
msgid "SHA256 sums file:"
msgstr "File di somma SHA256:"

#: share/mintstick/verify.ui.h:6
msgid "GPG signed file:"
msgstr "File firmato GPG:"

#: share/mintstick/verify.ui.h:8
msgid "URLs"
msgstr "URL"

#: share/mintstick/verify.ui.h:9
msgid "SHA256 sums file"
msgstr "File delle somme SHA256"

#: share/mintstick/verify.ui.h:10
msgid "GPG signed file"
msgstr "File firmato GPG"

#: share/mintstick/verify.ui.h:11
msgid "Local files"
msgstr "File locali"

#: share/mintstick/verify.ui.h:12
msgid "SHA256 sum"
msgstr "Somma SHA256"

#: share/mintstick/verify.ui.h:13
msgid "Check"
msgstr "Controlla"

#: share/mintstick/verify.ui.h:14
msgid "Checksum"
msgstr "Checksum"

#: share/mintstick/verify.ui.h:15
msgid "Go back"
msgstr "Indietro"

#: share/mintstick/verify.ui.h:16
msgid "ISO Verification"
msgstr "Verifica ISO"
