# Swedish translation for linuxmint
# Copyright (c) 2013 Rosetta Contributors and Canonical Ltd 2013
# This file is distributed under the same license as the linuxmint package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: linuxmint\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2023-11-27 14:33+0000\n"
"PO-Revision-Date: 2022-10-02 13:35+0000\n"
"Last-Translator: Jan-Olof Svensson <jan-olof.svensson@abc.se>\n"
"Language-Team: Swedish <sv@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2024-12-05 10:14+0000\n"
"X-Generator: Launchpad (build 1519c6efe8e9bd78e6c5ebf2eb5bcb040b95ad32)\n"

#: lib/mintstick.py:312
msgid "The USB stick was formatted successfully."
msgstr "USB-minnet har framgångsrikt formaterats."

#: lib/mintstick.py:315
#, python-format
msgid "An error occured while creating a partition on %s."
msgstr "Ett fel uppstod vid skapande av ny partion på %s."

#: lib/mintstick.py:317 lib/mintstick.py:427
msgid "Authentication Error."
msgstr "Autentiseringsfel."

#: lib/mintstick.py:322 lib/mintstick.py:433
msgid "An error occurred."
msgstr "Ett fel har uppstått."

#: lib/mintstick.py:420
msgid "The image was successfully written."
msgstr "Avbilden har skrivits."

#: lib/mintstick.py:423
msgid "Not enough space on the USB stick."
msgstr "Det är inte tillräckligt med utrymme på USB-minnet."

#: lib/mintstick.py:425
msgid "An error occured while copying the image."
msgstr "Ett fel uppstod vid kopiering av avbilden."

#: lib/verify.py:54
msgid "bytes"
msgstr "byte"

#: lib/verify.py:54
msgid "KB"
msgstr "KB"

#: lib/verify.py:54
msgid "MB"
msgstr "MB"

#: lib/verify.py:54
msgid "GB"
msgstr "GB"

#: lib/verify.py:54
msgid "TB"
msgstr "TB"

#: lib/verify.py:87
msgid "ISO images"
msgstr "ISO-avbilder"

#: lib/verify.py:91
msgid "Checksum files"
msgstr "Filer med kontrollsummor"

#: lib/verify.py:95
msgid "GPG signatures"
msgstr "GPG-signaturer"

#: lib/verify.py:107 lib/verify.py:108 lib/verify.py:109
msgid "Calculating..."
msgstr "Beräknar..."

#: lib/verify.py:167
msgid "No volume ID found"
msgstr "Hittade inget volym-ID"

#: lib/verify.py:208
msgid "The checksum is correct"
msgstr "Kontrollsumman stämmer"

#: lib/verify.py:209
msgid ""
"The checksum is correct but the authenticity of the sum was not verified."
msgstr "Kontrollsumman stämmer men dess äkthet kunde inte bekräftas."

#: lib/verify.py:211
msgid "Checksum mismatch"
msgstr "Kontrollsumman stämmer inte"

#: lib/verify.py:212
msgid "Download the ISO image again. Its checksum does not match."
msgstr "Hämta ISO-avbilden igen. Dess kontrollsumma stämmer inte."

#: lib/verify.py:223
msgid "The sums file could not be downloaded. Check the URL."
msgstr ""
"Filen med kontrollsummor kunde inte hämtas. Kontrollera webbadressen."

#: lib/verify.py:232
msgid "The gpg file could not be downloaded. Check the URL."
msgstr "GPG-filen kunde inte hämtas. Kontrollera webbadressen."

#: lib/verify.py:243
msgid "The sums file could not be checked."
msgstr "Filen med kontrollsummor kunde inte kontrolleras."

#: lib/verify.py:250
msgid "The gpg file could not be checked."
msgstr "GPG-filen kunde inte kontrolleras."

#: lib/verify.py:260
msgid "Integrity check failed"
msgstr "Integritetskontrollen misslyckades"

#: lib/verify.py:269
msgid "The SHA256 sums file is not signed."
msgstr "Filen med SHA256-summor är inte signerad."

#: lib/verify.py:273
#, python-format
msgid "Signed by: %s"
msgstr "Signerad av: %s"

#: lib/verify.py:287
msgid "Unknown signature"
msgstr "Okänd signatur"

#: lib/verify.py:288
msgid "Key not found on keyserver."
msgstr "Hittade inte nyckeln på nyckelservern."

#: lib/verify.py:299 lib/verify.py:305
msgid "Everything looks good!"
msgstr "Allt stämmer!"

#: lib/verify.py:300
msgid "This is an official ISO image."
msgstr "Detta är en officiell ISO-avbild."

#: lib/verify.py:306
msgid "This ISO image is verified by a trusted signature."
msgstr "ISO-avbilden har bekräftats med en betrodd signatur."

#: lib/verify.py:309
msgid "If you trust the signature you can trust the ISO."
msgstr "Om du litar på signaturen så kan du lita på ISO-avbilden."

#: lib/verify.py:310
msgid "Untrusted signature"
msgstr "Ej betrodd signatur"

#: lib/verify.py:311
msgid "This ISO image is verified by an untrusted signature."
msgstr "ISO-avbilden har bekräftats med en otillförlitlig signatur."

#: lib/verify.py:316
msgid "An error occurred"
msgstr "Ett fel uppstod"

#: lib/verify.py:327
msgid "The SHA256 sum of the ISO image is incorrect."
msgstr "SHA256-summan för ISO-avbilden stämmer inte."

#: lib/verify.py:328
msgid "The SHA256 sums file does not contain sums for this ISO image."
msgstr ""
"Filen med SHA256-summor innehåller ingen summa för den här ISO-avbilden."

#: generate_additional_files.py:22 generate_additional_files.py:34
#: share/mintstick/mintstick.ui.h:38
msgid "USB Image Writer"
msgstr "USB-avbildsskrivare"

#: generate_additional_files.py:22 generate_additional_files.py:34
#: generate_additional_files.py:67 share/mintstick/mintstick.ui.h:39
msgid "Make a bootable USB stick"
msgstr "Skapa ett startbart USB-minne"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: share/mintstick/mintstick.ui.h:27
msgid "USB Stick Formatter"
msgstr "USB-minnesformaterare"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:28
msgid "Format a USB stick"
msgstr "Formatera ett USB-minne"

#: generate_additional_files.py:67
msgid "Make bootable USB stick"
msgstr "Skapa startbart USB-minne"

#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:26
msgid "Format"
msgstr "Formatera"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:32
#: share/mintstick/verify.ui.h:7
msgid "Verify"
msgstr "Verifiera"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:33
msgid "Verify the authenticity and integrity of the image"
msgstr "Bekräfta avbildens äkthet och integritet."

#: generate_additional_files.py:115 generate_additional_files.py:144
msgid ""
"This will destroy all data on the USB stick, are you sure you want to "
"proceed?"
msgstr ""
"Detta kommer att radera allt som är lagrat på USB-minnet, är du säker på att "
"du vill fortsätta?"

#: share/mintstick/mintstick.ui.h:1
msgid "USB stick:"
msgstr "USB-minne:"

#: share/mintstick/mintstick.ui.h:2
msgid "Filesystem:"
msgstr "Filsystem:"

#: share/mintstick/mintstick.ui.h:3
msgid "Select a USB stick"
msgstr "Välj ett USB-minne"

#: share/mintstick/mintstick.ui.h:4
msgid ""
"FAT32 \n"
"  + Compatible everywhere.\n"
"  -  Cannot handle files larger than 4GB.\n"
"\n"
"exFAT\n"
"  + Compatible almost everywhere.\n"
"  + Can handle files larger than 4GB.\n"
"  -  Not as compatible as FAT32.\n"
"\n"
"NTFS \n"
"  + Compatible with Windows.\n"
"  -  Not compatible with Mac and most hardware devices.\n"
"  -  Occasional compatibility problems with Linux (NTFS is proprietary and "
"reverse engineered).\n"
"\n"
"EXT4 \n"
"  + Modern, stable, fast, journalized.\n"
"  + Supports Linux file permissions.\n"
"  -  Not compatible with Windows, Mac and most hardware devices.\n"
msgstr ""
"FAT32 \n"
"  + Fungerar med alla system.\n"
"  - Kan inte hantera filer som är större än 4 GB.\n"
"\n"
"exFAT\n"
"  + Fungerar med de flesta system.\n"
"  + Kan hantera filer som är större än 4 GB.\n"
"  - Inte lika vanligt som FAT32.\n"
"\n"
"NTFS \n"
"  + Fungerar med Windows.\n"
"  - Fungerar inte med Mac och de flesta inbyggda system.\n"
"  - Passar inte riktigt ihop med Linux (NTFS har stängd källkod vilket ger "
"problem).\n"
"\n"
"EXT4 \n"
"  + Ett modernt, snabbt och stabilt så kallat journalförande filsystem.\n"
"  + Har fullt stöd för rättigheter med mera i Linux.\n"
"  - Fungerar inte med Windows, Mac och de flesta inbyggda system.\n"

#: share/mintstick/mintstick.ui.h:23
msgid "Volume label:"
msgstr "Volymens text:"

#: share/mintstick/mintstick.ui.h:24
msgid "Choose a name for your USB Stick"
msgstr "Välj ett namn för ditt USB-minne"

#: share/mintstick/mintstick.ui.h:25
msgid "USB Stick"
msgstr "USB-minne"

#: share/mintstick/mintstick.ui.h:29
msgid "ISO image:"
msgstr "ISO-avbild:"

#: share/mintstick/mintstick.ui.h:30
msgid "Select an image"
msgstr "Välj avbild"

#: share/mintstick/mintstick.ui.h:31
msgid "Select Image"
msgstr "Välj avbild"

#: share/mintstick/mintstick.ui.h:34
msgid "Write"
msgstr "Skriv"

#: share/mintstick/mintstick.ui.h:35
msgid "This ISO looks like a Windows image."
msgstr "Det här verkar vara en avbild för Windows."

#: share/mintstick/mintstick.ui.h:36
msgid "Windows images require special processing."
msgstr "Avbilder för Windows kräver särskild behandling."

#: share/mintstick/mintstick.ui.h:37
msgid "More information"
msgstr "Mer information"

#: share/mintstick/verify.ui.h:1
msgid "ISO:"
msgstr "ISO:"

#: share/mintstick/verify.ui.h:2
msgid "Volume:"
msgstr "Volym:"

#: share/mintstick/verify.ui.h:3
msgid "SHA256sum:"
msgstr "SHA256-summa:"

#: share/mintstick/verify.ui.h:4
msgid "Size:"
msgstr "Storlek:"

#: share/mintstick/verify.ui.h:5
msgid "SHA256 sums file:"
msgstr "Fil med SHA256-summor:"

#: share/mintstick/verify.ui.h:6
msgid "GPG signed file:"
msgstr "GPG-signerad fil:"

#: share/mintstick/verify.ui.h:8
msgid "URLs"
msgstr "Webbadresser"

#: share/mintstick/verify.ui.h:9
msgid "SHA256 sums file"
msgstr "Fil med SHA256-summor"

#: share/mintstick/verify.ui.h:10
msgid "GPG signed file"
msgstr "GPG-signerad fil"

#: share/mintstick/verify.ui.h:11
msgid "Local files"
msgstr "Lokala filer"

#: share/mintstick/verify.ui.h:12
msgid "SHA256 sum"
msgstr "SHA256-summa"

#: share/mintstick/verify.ui.h:13
msgid "Check"
msgstr "Kontrollera"

#: share/mintstick/verify.ui.h:14
msgid "Checksum"
msgstr "Kontrollsumma"

#: share/mintstick/verify.ui.h:15
msgid "Go back"
msgstr "Gå tillbaka"

#: share/mintstick/verify.ui.h:16
msgid "ISO Verification"
msgstr "Kontroll av ISO"
