# Occitan (post 1500) translation for linuxmint
# Copyright (c) 2013 Rosetta Contributors and Canonical Ltd 2013
# This file is distributed under the same license as the linuxmint package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: linuxmint\n"
"Report-Msgid-Bugs-To: FULL NAME <EMAIL@ADDRESS>\n"
"POT-Creation-Date: 2023-11-27 14:33+0000\n"
"PO-Revision-Date: 2024-02-06 19:30+0000\n"
"Last-Translator: Quentin PAGÈS <Unknown>\n"
"Language-Team: Occitan (post 1500) <oc@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2025-01-06 11:56+0000\n"
"X-Generator: Launchpad (build 6394e03793719e8d73f5a60b5439440e693c92f1)\n"

#: lib/mintstick.py:312
msgid "The USB stick was formatted successfully."
msgstr "La clau USB es estada formatada amb succès."

#: lib/mintstick.py:315
#, python-format
msgid "An error occured while creating a partition on %s."
msgstr ""
"Una error s'es produita al moment de la creacion d'una particion sus %s."

#: lib/mintstick.py:317 lib/mintstick.py:427
msgid "Authentication Error."
msgstr "Error d'autentificacion."

#: lib/mintstick.py:322 lib/mintstick.py:433
msgid "An error occurred."
msgstr "Una error s'es produita."

#: lib/mintstick.py:420
msgid "The image was successfully written."
msgstr "L'imatge es estat escrit amb succès."

#: lib/mintstick.py:423
msgid "Not enough space on the USB stick."
msgstr "Pas pro d'espaci sus la clau USB."

#: lib/mintstick.py:425
msgid "An error occured while copying the image."
msgstr "Una error s'es produita al moment de la còpia de l'imatge."

#: lib/verify.py:54
msgid "bytes"
msgstr "octets"

#: lib/verify.py:54
msgid "KB"
msgstr "Ko"

#: lib/verify.py:54
msgid "MB"
msgstr "Mo"

#: lib/verify.py:54
msgid "GB"
msgstr "Go"

#: lib/verify.py:54
msgid "TB"
msgstr "To"

#: lib/verify.py:87
msgid "ISO images"
msgstr "Imatges ISO"

#: lib/verify.py:91
msgid "Checksum files"
msgstr "Soma de contraròtle"

#: lib/verify.py:95
msgid "GPG signatures"
msgstr "Signatura GPG"

#: lib/verify.py:107 lib/verify.py:108 lib/verify.py:109
msgid "Calculating..."
msgstr "Calcul en cors..."

#: lib/verify.py:167
msgid "No volume ID found"
msgstr "Cap d’ID de volum pas trobat"

#: lib/verify.py:208
msgid "The checksum is correct"
msgstr "La soma de contraròtle es corrècta"

#: lib/verify.py:209
msgid ""
"The checksum is correct but the authenticity of the sum was not verified."
msgstr ""
"La soma de contraròtle es corrècta mas l’autenticitat de la soma es pas "
"verificada."

#: lib/verify.py:211
msgid "Checksum mismatch"
msgstr "Non correspondéncia de la soma de contraròtle"

#: lib/verify.py:212
msgid "Download the ISO image again. Its checksum does not match."
msgstr ""
"Telecargatz l’imatge ISO de nòu. Sa soma de contraròtle correspond pas."

#: lib/verify.py:223
msgid "The sums file could not be downloaded. Check the URL."
msgstr "Se podiá pas telecargar la soma de contraròtle. Verificatz l’URL."

#: lib/verify.py:232
msgid "The gpg file could not be downloaded. Check the URL."
msgstr "Se podiá pas telecargar lo fichièr gpg. Verificatz l’URL."

#: lib/verify.py:243
msgid "The sums file could not be checked."
msgstr "Se podiá pas verificar la soma de contraròtle."

#: lib/verify.py:250
msgid "The gpg file could not be checked."
msgstr "Se podiá pas verificar lo fichièr gpg."

#: lib/verify.py:260
msgid "Integrity check failed"
msgstr "Pròva d’integritat pas capitada"

#: lib/verify.py:269
msgid "The SHA256 sums file is not signed."
msgstr "Lo fichièr SHA256 es pas signat."

#: lib/verify.py:273
#, python-format
msgid "Signed by: %s"
msgstr "Signat per : %s"

#: lib/verify.py:287
msgid "Unknown signature"
msgstr "Signatura desconeguda"

#: lib/verify.py:288
msgid "Key not found on keyserver."
msgstr "Clau pas trobada sul servidor de clau."

#: lib/verify.py:299 lib/verify.py:305
msgid "Everything looks good!"
msgstr "Tot sembla bon !"

#: lib/verify.py:300
msgid "This is an official ISO image."
msgstr "Aquò es un imatge ISO oficial."

#: lib/verify.py:306
msgid "This ISO image is verified by a trusted signature."
msgstr "Aqueste imatge ISO es pas verificat per una signatura fisabla."

#: lib/verify.py:309
msgid "If you trust the signature you can trust the ISO."
msgstr "Se vos fisatz de la signatura podètz vos fisar de l'ISO."

#: lib/verify.py:310
msgid "Untrusted signature"
msgstr "Signatura pas fisabla"

#: lib/verify.py:311
msgid "This ISO image is verified by an untrusted signature."
msgstr "Aqueste imatge ISO es verificat per una signatura pas fisabla."

#: lib/verify.py:316
msgid "An error occurred"
msgstr "Una error s'es producha"

#: lib/verify.py:327
msgid "The SHA256 sum of the ISO image is incorrect."
msgstr "La sòma SHA256 de l’imatge ISO es incorrècta."

#: lib/verify.py:328
msgid "The SHA256 sums file does not contain sums for this ISO image."
msgstr ""
"Lo fichièr de somas SHA256 conten pas cap de soma per aqueste imatge ISO."

#: generate_additional_files.py:22 generate_additional_files.py:34
#: share/mintstick/mintstick.ui.h:38
msgid "USB Image Writer"
msgstr "Creator de clau USB"

#: generate_additional_files.py:22 generate_additional_files.py:34
#: generate_additional_files.py:67 share/mintstick/mintstick.ui.h:39
msgid "Make a bootable USB stick"
msgstr "Crear una clau USB bootabla"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: share/mintstick/mintstick.ui.h:27
msgid "USB Stick Formatter"
msgstr "Formatador de clau USB"

#: generate_additional_files.py:46 generate_additional_files.py:58
#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:28
msgid "Format a USB stick"
msgstr "Formatar una clau USB"

#: generate_additional_files.py:67
msgid "Make bootable USB stick"
msgstr "Crear una clau USB bootabla"

#: generate_additional_files.py:77 share/mintstick/mintstick.ui.h:26
msgid "Format"
msgstr "Formatar"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:32
#: share/mintstick/verify.ui.h:7
msgid "Verify"
msgstr "Verificar"

#: generate_additional_files.py:86 share/mintstick/mintstick.ui.h:33
msgid "Verify the authenticity and integrity of the image"
msgstr "Verificar l’autenticitat e l’integritat de l’imatge"

#: generate_additional_files.py:115 generate_additional_files.py:144
msgid ""
"This will destroy all data on the USB stick, are you sure you want to "
"proceed?"
msgstr ""
"Totas las donadas presentas sus la clau USB seràn suprimidas. Volètz "
"contunhar ?"

#: share/mintstick/mintstick.ui.h:1
msgid "USB stick:"
msgstr "Clau USB :"

#: share/mintstick/mintstick.ui.h:2
msgid "Filesystem:"
msgstr "Sistèma de fichièrs :"

#: share/mintstick/mintstick.ui.h:3
msgid "Select a USB stick"
msgstr "Seleccionatz una clau USB"

#: share/mintstick/mintstick.ui.h:4
msgid ""
"FAT32 \n"
"  + Compatible everywhere.\n"
"  -  Cannot handle files larger than 4GB.\n"
"\n"
"exFAT\n"
"  + Compatible almost everywhere.\n"
"  + Can handle files larger than 4GB.\n"
"  -  Not as compatible as FAT32.\n"
"\n"
"NTFS \n"
"  + Compatible with Windows.\n"
"  -  Not compatible with Mac and most hardware devices.\n"
"  -  Occasional compatibility problems with Linux (NTFS is proprietary and "
"reverse engineered).\n"
"\n"
"EXT4 \n"
"  + Modern, stable, fast, journalized.\n"
"  + Supports Linux file permissions.\n"
"  -  Not compatible with Windows, Mac and most hardware devices.\n"
msgstr ""
"FAT32 \n"
"  + Compatible pertot.\n"
"  -  Pòt pas gerir los fichièrs de mai de 4Go.\n"
"\n"
"exFAT\n"
"  + Compatible gaireben pertot.\n"
"  + Pòt gerir los fichièrs de mai de 4Go.\n"
"  -  Pas tant compatible coma FAT32.\n"
"\n"
"NTFS \n"
"  + Compatible amb Windows.\n"
"  -  Non compatible amb Mac e los periferics materials.\n"
"  -  Problèmas de compatibilitat occasionals amb Linux (NTFS es proprietari "
"e retroconcebut).\n"
"\n"
"EXT4 \n"
"  + Modèrne, estable, rapid, jornalizat.\n"
"  + Pren en carga las autorizacions de fichièr Linux.\n"
"  -  Non compatible amb Windows, Mac e la màger part dels periferics.\n"

#: share/mintstick/mintstick.ui.h:23
msgid "Volume label:"
msgstr "Nom de volum :"

#: share/mintstick/mintstick.ui.h:24
msgid "Choose a name for your USB Stick"
msgstr "Causissètz un nom per vòstra clau USB"

#: share/mintstick/mintstick.ui.h:25
msgid "USB Stick"
msgstr "Clau USB"

#: share/mintstick/mintstick.ui.h:29
msgid "ISO image:"
msgstr "Imatge ISO :"

#: share/mintstick/mintstick.ui.h:30
msgid "Select an image"
msgstr "Seleccionatz un imatge"

#: share/mintstick/mintstick.ui.h:31
msgid "Select Image"
msgstr "Causissètz un imatge"

#: share/mintstick/mintstick.ui.h:34
msgid "Write"
msgstr "Escriure"

#: share/mintstick/mintstick.ui.h:35
msgid "This ISO looks like a Windows image."
msgstr "Aquò sembla un imatge Windows."

#: share/mintstick/mintstick.ui.h:36
msgid "Windows images require special processing."
msgstr "Los imatges Windows requèron un tractament especial."

#: share/mintstick/mintstick.ui.h:37
msgid "More information"
msgstr "Mai d'informacions"

#: share/mintstick/verify.ui.h:1
msgid "ISO:"
msgstr "ISO :"

#: share/mintstick/verify.ui.h:2
msgid "Volume:"
msgstr "Volum :"

#: share/mintstick/verify.ui.h:3
msgid "SHA256sum:"
msgstr "Soma SHA256 :"

#: share/mintstick/verify.ui.h:4
msgid "Size:"
msgstr "Talha :"

#: share/mintstick/verify.ui.h:5
msgid "SHA256 sums file:"
msgstr "Fichièr de somas SHA256 :"

#: share/mintstick/verify.ui.h:6
msgid "GPG signed file:"
msgstr "Fichièr GPG signat :"

#: share/mintstick/verify.ui.h:8
msgid "URLs"
msgstr "URL"

#: share/mintstick/verify.ui.h:9
msgid "SHA256 sums file"
msgstr "Fichièr de somas SHA256"

#: share/mintstick/verify.ui.h:10
msgid "GPG signed file"
msgstr "Fichièr GPG signat"

#: share/mintstick/verify.ui.h:11
msgid "Local files"
msgstr "Fichièrs locals"

#: share/mintstick/verify.ui.h:12
msgid "SHA256 sum"
msgstr "Soma SHA256"

#: share/mintstick/verify.ui.h:13
msgid "Check"
msgstr "Verificar"

#: share/mintstick/verify.ui.h:14
msgid "Checksum"
msgstr "Soma de contraròtle"

#: share/mintstick/verify.ui.h:15
msgid "Go back"
msgstr "Retorn"

#: share/mintstick/verify.ui.h:16
msgid "ISO Verification"
msgstr "Verificacion ISO"
